// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSchoolControl.Server.Db;

#nullable disable

namespace SmartSchoolControl.Server.Db.Migrations
{
    [DbContext(typeof(ServerSqLiteDbContext))]
    [Migration("20220404162028_AddClientInfo")]
    partial class AddClientInfo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("ClientScheduledTask", b =>
                {
                    b.Property<Guid>("ClientsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TasksId")
                        .HasColumnType("TEXT");

                    b.HasKey("ClientsId", "TasksId");

                    b.HasIndex("TasksId");

                    b.ToTable("ClientScheduledTask");
                });

            modelBuilder.Entity("SmartSchoolControl.Common.Base.ApiModels.Packages.Requests.ClientInfo", b =>
                {
                    b.Property<string>("Display")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Display");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientInfo");
                });

            modelBuilder.Entity("SmartSchoolControl.Common.Base.DbModels.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastHeartBeatTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedAssociations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("SmartSchoolControl.Common.Base.DbModels.ScheduledTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientsExecutionTimes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("SmartSchoolControl.Common.Base.DbModels.TaskAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PluginId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.ToTable("TaskActions");
                });

            modelBuilder.Entity("SmartSchoolControl.Common.Base.DbModels.TaskTrigger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DateTimes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dates")
                        .HasColumnType("TEXT");

                    b.Property<string>("DayInWeek")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExecutionOnceTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ScheduledTaskId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimesInDay")
                        .HasColumnType("TEXT");

                    b.Property<short>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledTaskId");

                    b.ToTable("TaskTriggers");
                });

            modelBuilder.Entity("SmartSchoolControl.Common.Base.DbModels.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<short>("WorkflowExecutionFailedAction")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Workflows");
                });

            modelBuilder.Entity("ClientScheduledTask", b =>
                {
                    b.HasOne("SmartSchoolControl.Common.Base.DbModels.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchoolControl.Common.Base.DbModels.ScheduledTask", null)
                        .WithMany()
                        .HasForeignKey("TasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartSchoolControl.Common.Base.ApiModels.Packages.Requests.ClientInfo", b =>
                {
                    b.HasOne("SmartSchoolControl.Common.Base.DbModels.Client", null)
                        .WithMany("ClientInfos")
                        .HasForeignKey("ClientId");
                });

            modelBuilder.Entity("SmartSchoolControl.Common.Base.DbModels.ScheduledTask", b =>
                {
                    b.HasOne("SmartSchoolControl.Common.Base.DbModels.Workflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("SmartSchoolControl.Common.Base.DbModels.TaskAction", b =>
                {
                    b.HasOne("SmartSchoolControl.Common.Base.DbModels.Workflow", null)
                        .WithMany("TaskActions")
                        .HasForeignKey("WorkflowId");
                });

            modelBuilder.Entity("SmartSchoolControl.Common.Base.DbModels.TaskTrigger", b =>
                {
                    b.HasOne("SmartSchoolControl.Common.Base.DbModels.ScheduledTask", null)
                        .WithMany("Triggers")
                        .HasForeignKey("ScheduledTaskId");
                });

            modelBuilder.Entity("SmartSchoolControl.Common.Base.DbModels.Client", b =>
                {
                    b.Navigation("ClientInfos");
                });

            modelBuilder.Entity("SmartSchoolControl.Common.Base.DbModels.ScheduledTask", b =>
                {
                    b.Navigation("Triggers");
                });

            modelBuilder.Entity("SmartSchoolControl.Common.Base.DbModels.Workflow", b =>
                {
                    b.Navigation("TaskActions");
                });
#pragma warning restore 612, 618
        }
    }
}
