// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolComputerControl.Server.Endpoints.ConfigurationEndpoints;

#nullable disable

namespace SchoolComputerControl.Server.Migrations
{
    [DbContext(typeof(ServerDbContext))]
    [Migration("20220901091908_202209011719")]
    partial class _202209011719
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("SchoolComputerControl.Infrastructure.Models.DbModels.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("SchoolComputerControl.Infrastructure.Models.DbModels.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClientActionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Configs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastHeartBeat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientActionId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("SchoolComputerControl.Infrastructure.Models.DbModels.ClientAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ClientActions");
                });

            modelBuilder.Entity("SchoolComputerControl.Infrastructure.Requests.ClientPluginAction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionParameter")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClientActionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientActionId");

                    b.ToTable("ClientPluginAction");
                });

            modelBuilder.Entity("SchoolComputerControl.Infrastructure.Models.DbModels.Client", b =>
                {
                    b.HasOne("SchoolComputerControl.Infrastructure.Models.DbModels.ClientAction", null)
                        .WithMany("Clients")
                        .HasForeignKey("ClientActionId");
                });

            modelBuilder.Entity("SchoolComputerControl.Infrastructure.Requests.ClientPluginAction", b =>
                {
                    b.HasOne("SchoolComputerControl.Infrastructure.Models.DbModels.ClientAction", null)
                        .WithMany("Actions")
                        .HasForeignKey("ClientActionId");
                });

            modelBuilder.Entity("SchoolComputerControl.Infrastructure.Models.DbModels.ClientAction", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
